### ISSUE TITLE
[WISH] Could this package generate urls to hyperkitty from emails open in message mode?

### ISSUE THREAD

**Issue by D4N** [maxking/hyperkitty.el#12]
This might be pretty far fetched, but would it be possible for this package to generate/retrieve the url to the message that is currently open in message mode? This can of course only really work if there was a way how to search for message by ids or other headers on hyperkitty, but if there was a way, that would be a **very** handy feature to have!

**Comment by maxking** [comment]
It should be pretty easy actually to do that, we have all the parameters available, including the list name, message-id-hash and ofcourse the base-url of the server.

What I don't know is how to get the message-id of the message at point since there isn't any structure when I print them to the current buffer and they are simply text. But I'll take a look and see what to do. 

Regardless, I should be able to open the thread page in Hyperkitty without knowing the message at point, although, being able to do that would be better.

**Comment by maxking** [comment]
Although, I can always add a button to open in HK when printing emails though, that should be trivial. I was already planning to add one to reply with a `mailto:` link of the list.

**Comment by D4N** [comment]
> Regardless, I should be able to open the thread page in Hyperkitty without knowing the message at point

That would definitely be pretty handy to have. Finding the correct message is usually relatively simple in hyperkitty, but finding the right thread on a high volume ML is the time consuming part.
